[package]
name = "jiggle"
version = "0.1.0"
edition = "2021"
authors = ["Piszmog"]

[profile.release]
# https://github.com/johnthagen/min-sized-rust
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
clap = { version = "4.3.5", features = ["derive"] }
